/// <reference types="node" />
import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import {
  MEDIAPIPE_REQUIRED_ASSETS,
  mediapipeAssetUrl,
  mediapipeLocateFile,
} from '../app/utils/mediapipeAssets';

/**
 * The pose engine must load from the app bundle.
 *
 * It used to be pulled from cdn.jsdelivr.net at runtime, which works in a
 * browser but breaks a shipped APK with no network — and that is the whole
 * point of this being an app. These tests fail if a remote URL is reintroduced
 * or if the vendor step stops producing the files the runtime asks for.
 */

const srcRoot = join(__dirname, '..');

/**
 * Every .ts/.tsx file under src/, so a CDN reference anywhere is caught.
 * Tests are skipped: this file names the CDNs it is looking for, and would
 * otherwise always fail against itself.
 */
const sourceFiles = (): string[] => {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name !== '__tests__') walk(full);
      } else if (/\.tsx?$/.test(entry.name)) {
        out.push(full);
      }
    }
  };
  walk(srcRoot);
  return out;
};

describe('MediaPipe offline vendoring', () => {
  it('no source file loads the pose engine from a CDN', () => {
    const offenders = sourceFiles().filter((f) => /cdn\.jsdelivr\.net|unpkg\.com/.test(readFileSync(f, 'utf8')));
    expect(offenders).toEqual([]);
  });

  it('resolves runtime files to a bundled, same-origin path', () => {
    const url = mediapipeLocateFile('pose_solution_simd_wasm_bin.wasm');
    expect(url).toBe('/mediapipe/pose/pose_solution_simd_wasm_bin.wasm');
    expect(url.startsWith('/')).toBe(true);
    expect(url).not.toMatch(/^https?:/);
  });

  it('keeps the base path so a sub-path deployment still resolves', () => {
    expect(mediapipeAssetUrl('x')).toBe(mediapipeLocateFile('x'));
  });

  it('vendored assets exist after the vendor step has run', () => {
    // public/mediapipe is generated by scripts/vendor-mediapipe.mjs and is
    // gitignored, so this is a real check that `npm run vendor:mediapipe` ran.
    const dir = join(srcRoot, '..', 'public', 'mediapipe', 'pose');
    expect(existsSync(dir)).toBe(true);
    for (const asset of MEDIAPIPE_REQUIRED_ASSETS) {
      const file = join(dir, asset);
      expect(existsSync(file), `${asset} is missing — run "npm run vendor:mediapipe"`).toBe(true);
      expect(readFileSync(file).length).toBeGreaterThan(0);
    }
  });
});
